// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXWQqrT-1cKqfl8ImAnDXnk654cCbsnfw',
    appId: '1:206192041033:web:d32ead7bef0d1081aa3398',
    messagingSenderId: '206192041033',
    projectId: 'maghanem-1',
    authDomain: 'maghanem-1.firebaseapp.com',
    storageBucket: 'maghanem-1.firebasestorage.app',
    measurementId: 'G-WLKP2Z2ZB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwSSer0TQLAug2xzVswYXUquTW4GIcKWk',
    appId: '1:206192041033:android:2a2791b1ef9169ccaa3398',
    messagingSenderId: '206192041033',
    projectId: 'maghanem-1',
    storageBucket: 'maghanem-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApck1udbtzb5DD4jmMSzw_k8OGN1aZXjc',
    appId: '1:206192041033:ios:f4e5c5ce0f0c03a1aa3398',
    messagingSenderId: '206192041033',
    projectId: 'maghanem-1',
    storageBucket: 'maghanem-1.firebasestorage.app',
    androidClientId: '206192041033-7l22tkse63kmd06brjhend6bps5uiamq.apps.googleusercontent.com',
    iosClientId: '206192041033-8ifg7dfgndj37gfjt5h1e0dl2tlsb0ik.apps.googleusercontent.com',
    iosBundleId: 'com.moskaoud.maghanem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApck1udbtzb5DD4jmMSzw_k8OGN1aZXjc',
    appId: '1:206192041033:ios:f4e5c5ce0f0c03a1aa3398',
    messagingSenderId: '206192041033',
    projectId: 'maghanem-1',
    storageBucket: 'maghanem-1.firebasestorage.app',
    androidClientId: '206192041033-7l22tkse63kmd06brjhend6bps5uiamq.apps.googleusercontent.com',
    iosClientId: '206192041033-8ifg7dfgndj37gfjt5h1e0dl2tlsb0ik.apps.googleusercontent.com',
    iosBundleId: 'com.moskaoud.maghanem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXWQqrT-1cKqfl8ImAnDXnk654cCbsnfw',
    appId: '1:206192041033:web:844f767f62b066d8aa3398',
    messagingSenderId: '206192041033',
    projectId: 'maghanem-1',
    authDomain: 'maghanem-1.firebaseapp.com',
    storageBucket: 'maghanem-1.firebasestorage.app',
    measurementId: 'G-FQ9CEZ26JD',
  );

}